bowlingvo/bowlingvo/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from . import configs


from django.shortcuts import redirect
def to_main(request):
    return redirect('/main/')


urlpatterns = [
    path('', to_main),
    path('admin/', admin.site.urls),
    path('main/', include('main.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bowlingvo/main/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, re_path, include
from .forms import LoginForm

from . import views

# from django.conf import urls
# urls.handler404 = 'main.views.handler404'  # page not found
# urls.handler500 = 'main.views.handler500'  # server error
# urls.handler403 = 'main.views.handler403'  # permission denied
# urls.handler400 = 'main.views.handler400'  # bad request


urlpatterns = [
    path('test', views.test),
]


authentication_patterns = [
    path('login', auth_views.LoginView.as_view(template_name='main/login_form.html', form_class=LoginForm,
                                               redirect_authenticated_user=True), name='login'),
    path('do-logout', auth_views.LogoutView.as_view(), name='logout'),
    path('register', views.RegistrationView.as_view(), name='register'),
    path('reset', auth_views.PasswordResetView.as_view(template_name='main/password_reset_form.html', )),
    path('done', auth_views.PasswordResetDoneView.as_view(template_name='main/password_reset_done.html'),
         name='password_reset_done'),
    re_path(r'^confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            auth_views.PasswordResetConfirmView.as_view(success_url='/main',
                                                        template_name='main/password_reset_confirm.html'),
            name='password_reset_confirm'),
]


profile_patterns = [
    path('profile', views.get_profile, name='profile'),
    path('edit-profile', views.sorry, name='edit_profile'),
    path('avatar/', include('avatar.urls'), name='avatar'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.activate,
            name='activate'),
]


educational_patterns = [
    path('', views.index, name='index'),
    path('lang/<str:language_name>', views.language_page, name='language'),
    path('lang/<str:language_name>/sec/<str:section_name>', views.section_page, name='section'),
    path('lang/<str:language_name>/sec/<str:section_name>/les/<int:lesson_order>', views.lesson_page, name='lesson'),
]


game_patterns = [
    path('lang/<str:language_name>/startgame', views.GameStartView.as_view(), name='startgame'),
    path('lang/<str:language_name>/game', views.GameView.as_view(), name='game'),
    path('lang/<str:language_name>/endgame', views.endgame, name='endgame'),
]


urlpatterns += authentication_patterns
urlpatterns += profile_patterns
urlpatterns += educational_patterns
urlpatterns += game_patterns

bowlingvo/main/models.py
from django.db import models
from django.contrib.auth.models import User


class Language(models.Model):
    objects = models.Manager()

    name = models.CharField(max_length=64)
    url_name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Section(models.Model):
    objects = models.Manager()

    name = models.CharField(max_length=64)
    url_name = models.CharField(max_length=50)
    language = models.ForeignKey(Language, on_delete=models.CASCADE)
    sec_type = models.CharField(max_length=1, default='L')

    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return str(self.language) + '-/-' + str(self.name) + '(' + str(self.sec_type) + ')'


class Lesson(models.Model):
    objects = models.Manager()

    section = models.ForeignKey(Section, on_delete=models.CASCADE)

    order = models.IntegerField(default=1)

    def __str__(self):
        return str(self.section) + '-/-' + str(self.order)


class Key2Lesson(models.Model):
    objects = models.Manager()

    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    key = models.CharField(max_length=64, db_index=True)

    def __str__(self):
        return str(self.lesson) + ' | ' + str(self.key)


class Word(models.Model):
    objects = models.Manager()

    key = models.CharField(max_length=64, db_index=True)
    language = models.CharField(max_length=50)
    sing_form = models.TextField()
    plur_form = models.TextField()

    def __str__(self):
        return str(self.language) + '-/-' + str(self.sing_form)
        

class Phrase(models.Model):
    objects = models.Manager()

    key = models.CharField(max_length=64, db_index=True)
    language = models.CharField(max_length=50)
    text = models.TextField()
    answer = models.TextField()

    def __str__(self):
        return self.key


class TheoryUnit(models.Model):
    objects = models.Manager()

    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    theory = models.TextField()


class TheoryTask(models.Model):
    objects = models.Manager()

    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    type = models.CharField(max_length=1, default='C')
    task = models.TextField()
    answer = models.CharField(max_length=32)


class FinishedLesson(models.Model):
    objects = models.Manager()

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now=True)


class FinishedSection(models.Model):
    objects = models.Manager()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    section = models.ForeignKey(Section, on_delete=models.CASCADE)


class FinishedLanguage(models.Model):
    objects = models.Manager()

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    language = models.ForeignKey(Language, on_delete=models.CASCADE)


class UserProfile(models.Model):
    objects = models.Manager()

    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    score = models.IntegerField(default=0)
    last_lang = models.IntegerField(default=0)

    def __str__(self):
        return str(self.user)


class FrameRecord(models.Model):
    objects = models.Manager()

    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    max_frames = models.IntegerField()
    cur_frame = models.IntegerField(default=0)
    score_table = models.TextField(default='[]')
    frame_score = models.IntegerField(default=0)

    def __str__(self):
        return str(self.user)

bowlingvo/main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        label='Логин:',
        widget=forms.TextInput(attrs={'autofocus': True, 'placeholder': 'Логин'})
    )
    password = forms.CharField(
        label='Пароль:',
        strip=False,
        widget=forms.PasswordInput(attrs={'placeholder': 'Пароль'})
    )


class RegistrationForm(UserCreationForm):
    username = forms.CharField(
        label='Логин:',
        required=True,
        widget=forms.TextInput(attrs={'autofocus': True, 'placeholder': 'Логин'})
    )
    email = forms.EmailField(
        label='Email:',
        required=True,
        help_text="Введите правильный email.",
        widget=forms.TextInput(attrs={'placeholder': 'Email'})
    )
    password1 = forms.CharField(
        label='Пароль:',
        required=True,
        strip=False,
        widget=forms.PasswordInput(attrs={'placeholder': 'Пароль'}),
    )
    password2 = forms.CharField(
        label='Повторите пароль:',
        required=True,
        strip=False,
        widget=forms.PasswordInput(attrs={'placeholder': 'Повторите пароль'}),
    )

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class EditProfileForm(PasswordChangeForm):
    username = forms.CharField(
        label='Сменить имя пользователя:',
        required=False,
        max_length=150,
        widget=forms.TextInput(attrs={'placeholder': 'Имя пользователя'})
    )
    email = forms.EmailField(
        label='Сменить email (требуется подтверждение):',
        required=False,
        help_text="Введите правильный email.",
        widget=forms.TextInput(attrs={'placeholder': 'Email'})
    )
    old_password = forms.CharField(
        label='Введите старый пароль:',
        required=False,
        strip=False,
        help_text='Введите старый пароль.',
        widget=forms.PasswordInput(attrs={'placeholder': 'Старый пароль'}),
    )
    new_password1 = forms.CharField(
        label='Введите новый пароль:',
        required=False,
        strip=False,
        help_text='Введите новый пароль.',
        widget=forms.PasswordInput(attrs={'placeholder': 'Новый пароль'}),
    )
    new_password2 = forms.CharField(
        label='Повторите новый пароль:',
        required=False,
        strip=False,
        help_text='Повторите новый пароль.',
        widget=forms.PasswordInput(attrs={'placeholder': 'Повторите новый пароль'}),
    )

bowlingvo/main/views.py
from .additional_views.authorization_views import *
from .additional_views.profile_views import *
from .additional_views.education_views import *
from .additional_views.game_views import *
from .additional_views.error_views import *
from .additional_views.test_views import *
from django.shortcuts import render


def sorry(request):
    return render(request, 'main/sorry.html')

bowlingvo/main/templates/main/acc_activation.html
Здравствуйте, {{ user.username }},
Пожалуйста, перейдите по следующей ссылке, чтобы подтвердить почту,
http://{{ domain }}/main/activate/{{ uid }}/{{ token }}

bowlingvo/main/templates/main/change_avatar.html
{% load avatar_tags %}
{% include 'main/header.html' %}

<div class="avatar-back">
	<h1>Изменение аватара профиля</h1>
    <div class="current-avatar">
        {% avatar user 175 %}
		<p>Текущий аватар</p>
    </div>
    {% if not avatars %}
        <div class="avatar-error">Нет аватаров</div>
    {% else %}
		<p>Выбрать из загруженных</p>
        <form method="POST" action="{% url 'avatar_change' %}" id="avatar-change-form">
            {% for field in primary_avatar_form %}
                {% for choice in field %}
                    {{ choice }}
                {% endfor %}
            {% endfor %}
            {% csrf_token %}
			<a class='remove-avatar' href="/main/avatar/delete">Удалить аватары</a>
            <input type='submit' class='avatar-change-button' value='Установить'>
        </form>
    {% endif %}
	<p>Добавить аватар</p>
    <form enctype="multipart/form-data" method="POST" action="{% url 'avatar_add' %}" id="avatar-addition-form">
        {{ upload_avatar_form }}
        {% csrf_token %}
		<label for='id_avatar' class='upload-avatar'>Выбрать изображение</label>
		<p class='avatar-addition-attention'>Сайт автоматически обрезает загружаемые изображения. Рекомендуем загружать квадратные фотографии</p>
        <input type='submit' value='Добавить'>
    </form>
	<a href="/main/profile" class='avatar-to-profile'>Вернуться в профиль</a>
</div>

{% include 'main/footer.html' %}

bowlingvo/main/templates/main/edit_profile.html
{% include "main/header.html" %}

{% for s in success %}
    {{ s }}<br>
{% endfor %}
<form action="{% url 'edit_profile' %}" method="post">
    {% csrf_token %}
    {% for er in errors.username %}
        {{ er|escape }}<br>
    {% endfor %}
    <input type="text" name="username" placeholder="Сменить имя пользователя">
    {% for er in errors.email %}
        {{ er|escape }}<br>
    {% endfor %}
    <input type="text" name="email" placeholder="Сменить email">
    {% for er in errors.old_password %}
        {{ er|escape }}<br>
    {% endfor %}
    <input type="password" name="old_password" placeholder="Старый пароль">
    {% for er in errors.new_password1 %}
        {% for e in er %}
            {{ e|escape }}<br>
        {% endfor %}
    {% endfor %}
    <input type="password" name="new_password1" placeholder="Новый пароль">
    {% for er in errors.new_password2 %}
        {{ er|escape }}<br>
    {% endfor %}
    <input type="password" name="new_password2" placeholder="Повторите пароль">
    <input type="submit" value="Сохранить">
</form>
<a href="{% url 'profile' %}">Назад</a>
{% include "main/footer.html" %}

bowlingvo/main/templates/main/email_conf.html
{% include "main/header.html" %}
<div class='the_letter_was_sent'>
	Аккаунт успешно создан<br>
	Письмо с подтверждением было отправлено на адрес <span>{{ email }}</span>
</div>
{% include "main/footer.html" %}

bowlingvo/main/templates/main/head.html
{% load static %}
<head>
    <meta charset="utf-8">
    <title>BowLingvo</title>
    <meta name="keywords" content="">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
	<link href="{% static 'main/images/favicon.ico' %}" rel="shortcut icon">
    <link rel="stylesheet" href="{% static 'main/index.css' %}" type="text/css">
</head>

bowlingvo/main/templates/main/header.html
{% load static %}
{% load avatar_tags %}
{% include "main/head.html" %}
<div class="container">
    <div class="header">
        <a href="/main/"><img id='logo' src="{% static 'main/images/logo.png' %}" alt="bowlingvo logo"></a>
        <a href="/main/"><div id="brand">BowLingvo</div></a>
        {% if user.is_authenticated %}
            {% if not is_profile %}
                <input type='text' id='submenu-position'>
                <div id="user"><label for='submenu-position'>{{ user.username }}</label>
                    <div class='header-submenu'>
                        <a href='/main/profile'>Профиль</a>
						<div></div>
						{% if user.is_superuser %}
                            <a href="/admin">Админка</a>
                            <div></div>
                        {% endif %}
                        <a href='/main/do-logout'>Выход</a>
		            </div>
                </div>
                <label for='submenu-position' class='label-submenu-avatar'>{% avatar user id='header-avatar' %}</label>
            {% endif %}
        {% else %}
            <a href="/main/register" id="register-button">Регистрация</a>
            <a href="/main/login" id="login-button">Вход</a>
        {% endif %}
    </div>
    <div class="content">

bowlingvo/main/templates/main/index.html
{% load static %}
{% include "main/header.html" %}

<div class='content'>
	<h1 class='greetings'>Добро пожаловать!</h1>
    <div class='course'>
        Выберите курс:
    </div>
    <div class='languages'>
        {% for language in languages %}
		<div class='lang'><a href="{% url 'language' language_name=language.url_name %}">
			<div class='flag'>
                {% with 'main/images/'|add:language.url_name|add:'-flag.png' as flag_image %}
                <img src="{% static flag_image %}" alt='language flag' class='flag-icon'>
                {% endwith %}
			</div
			><div class='language-name'>
				{{ language.name }}
            </div>
        </a></div>
        {% endfor %}
    </div>
</div>

{% include "main/footer.html" %}

bowlingvo/main/templates/main/language_page.html
{% load static %}
{% include "main/header.html" %}

<div class='page-head'>
	<div class='go-back'><a href="/main/">&#8962</a></div>
	<div class='page-name'>
		{{ language.name }}
	</div>
</div>

<div class='all-sections'>
    <div class='type-choices'>
        <div id='lex-button' class='highlight' onclick="show_lex()">Лексика</div>
        <div id='gram-button' onclick="show_gram()">Грамматика</div>
    </div>
    <div id='lex-sections'>
        {% for section, ability in lex_sections %}
        <a href="{% url 'section' language_name=language.url_name section_name=section.url_name %}"><div class='lex-sec {{ ability }}'>
            <div class='sec-logo'>
				{% with 'main/images/sections/section-'|add:section.url_name|add:'.png' as section_image %}
				<img src="{% static section_image %}">
				{% endwith %}
            </div>
            <div class='sec-name'>
                {{ section.name }}
            </div>
        </div></a>
        {% endfor %}
    </div>
    <div hidden id='gram-sections'>
        {% if gram_sections %}
            {% for section, ability in gram_sections %}
            <div class='gram-path {{ ability }}'>
                <div class='gram-path-left'>˅</div>
                <div class='gram-path-right'>˅</div>
            </div>
            <div class='gram-sec {{ ability }}'>
                {% if ability != 'locked' %}
                    <a href="{% url 'section' language_name=language.url_name section_name=section.url_name %}">
                {% endif %}
                    <div class='padding-right'></div>
                    <div class='sec-name'>
                        {{ section.name }}
                    </div>
                    <div class='sec-url'>
                {% if ability != 'locked' %}
                    выбрать
                {% else %}
                    недоступен
                {% endif %}
                    </div>
                {% if ability != 'locked' %}
                    </a>
                {% endif %}
            </div>
            {% endfor %}
        {% else %}
            <h2>Извините, для данного языка пока нет грамматических тем</h2>
        {% endif %}
    </div>
</div>

<div>
	<a href="{% url 'startgame' language_name=language.url_name %}" class='start-game-button'>Начать игру</a>
</div>

{% include "main/footer.html" %}

bowlingvo/main/templates/main/lesson_page.html
{% include "main/header.html" %}

<div class='page-head'>
    <div class='go-back'><a href="{% url 'section' language_name=language.url_name section_name=section.url_name %}"><</a></div>
    <div class='page-name'>
        {{ section.name }} {{ lesson.order }}
    </div>
</div>

<div class='lesson-content'>
    <div id='all-tasks'>
        <div id='task0'>
            {% if type == 'L' %}
    			<div class='subheader'>Слова к уроку</div>
                {% for theory_unit in theory %}
                <div class='word'>
                    <div>{{ theory_unit.for_sing }}</div>
                    <div>{{ theory_unit.rus_sing }}</div>
                    <div>{{ theory_unit.for_plur }}</div>
                    <div>{{ theory_unit.rus_plur }}</div>
                </div>
                {% endfor %}
            {% else %}
                {% autoescape off %}
                {{ theory }}
                {% endautoescape %}
            {% endif %}
        </div>
        {% for task in tasks %}
        {% with cur_val=forloop.counter %}
        <div hidden class='task' id='task{{ cur_val }}' answer='{{ task.answer }}'>
            <div class='target'>
                {% if task.type == 'input' %}
                    <div>Введите слово в нужной форме</div>
                    {% if type == 'L' %}
                        {{ task.text.0 }}{{ task.text.1 }}{{ task.text.2 }}<br>
                        {{ task.text.3 }}_____{{ task.text.4 }}
                    {% else %}
                        {{ task.text.0 }}_____{{ task.text.1 }}
                    {% endif %}
                {% else %}
                    {% if type == 'L' %}
					    <div>Выберите правильный перевод слова</div>
                    {% else %}
                        <div>Выберите правильный ответ</div>
                    {% endif %}
                    {{ task.text.0 }}
                {% endif %}
            </div>
			<div class='answer'>
				{% if task.type == 'input' %}
				<input autofocus type='text' name='user-answer-{{ cur_val }}' class='answer-text'>
				{% else %}
                {% for var in task.choices %}
                <div><label><input type='radio' name='user-answer-{{ cur_val }}' value='{{ var }}' class='radio'><span class='label-radio'>{{ var }}</span></label></div>
                {% endfor %}
				{% endif %}
			</div>
        </div>
        {% endwith %}
        {% endfor %}
        <div class='navig'>
			<div hidden id='correct-answer'>Верно</div>
			<div hidden id='wrong-answer'>
				Неверно
				<div id='your-answer'></div>
				<div id='expected-answer'></div>
			</div>
			<button id='task-button' onclick='lesson.getNext()'>Начать</button>
		</div>
	</div>
    <div hidden class='finish' id='finish'>
        <p>Вы закончили урок</p>
        <p>Ваши очки:</p>
        <div id='lesson-score'></div>
        <form action="{% url 'lesson' language_name=language.url_name section_name=section.url_name lesson_order=lesson.order %}" method='post'>
            {% csrf_token %}
            <input hidden name='score' type='text' id='score-input'>
            <input type='submit' id='finish-button' value='Завершить'>
        </form>
    </div>
</div>

{% include "main/footer.html" %}

bowlingvo/main/templates/main/login_form.html
{% include "main/header.html" %}
<div class="login-back">
    <div class="authorization-description">
        <h1>Авторизация</h1>
    {% if form.errors %}
        <div class="login-error">
            Неправильный логин или пароль. Обратите внимание, <br> что оба поля могут быть чувствительны к регистру
        </div>
    {% else %}
        <div class="authorization-instructions">
            Пожалуйста, заполните данные поля. Обратите внимание, <br> что оба поля могут быть чувствительны к регистру
        </div>
    {% endif %}
    </div>
    <form action="{{ app_path }}" method="post" id="login-form">
        {% csrf_token %}
        <div class="authorization-label">{{ form.username.label }}</div>
        {{ form.username }}
        <div class="authorization-label">{{ form.password.label }}</div>
        {{ form.password }}
		<a href='/main/reset'>Забыли пароль?</a>
        <input type="hidden" name="next" value="{{ next }}" />
        <input class="authorization-submit" type="submit" value="Войти">
    </form>
</div>
{% include "main/footer.html" %}

bowlingvo/main/templates/main/password_reset_confirm.html
{% include "main/header.html" %}

<div class='password-reset'>
	{% if validlink %}
		<p>Введите новый пароль в оба поля</p>
		<form method='post' class='password-confirm'>
			{% csrf_token %}
			{{ form.new_password1.errors }}
			{{ form.new_password2.errors }}
			<label for='id_new_password1'>Новый пароль:</label>
			{{ form.new_password1 }}
			<label for='id_new_password2'>Повторите пароль:</label>
			{{ form.new_password2 }}
			<input type='submit' value='Изменить пароль' class='reset-confirm'>
		</form>
	{% else %}
	<p>
		Ссылка для восстановления пароля недействительна.<br>
		Запросите новую.
	</p>
	{% endif %}
</div>

{% include "main/footer.html" %}

bowlingvo/main/templates/main/registration_form.html
{% include "main/header.html" %}
<div class="register-back">
    <div class="authorization-description">
        <h1>Регистрация</h1>
    {% if form.errors %}
        <div class="register-error">
            {% for field in form %}
                {% if field.errors %}
                    {% for error in field.errors %}
                        {{ error|escape }}<br>
                    {% endfor %}
                {% endif %}
            {% endfor %}
        </div>
    {% else %}
        <div class="authorization-instructions">
            Пожалуйста, заполните данные поля. Обратите внимание, <br> что поля могут быть чувствительны к регистру
        </div>
    {% endif %}
    </div>
    <form action="{{ app_path }}" method="post" id="register-form">
        {% csrf_token %}
        <div class="authorization-label">{{ form.username.label }}</div>
        {{ form.username }}
        <div class="authorization-label">{{ form.email.label }}</div>
        {{ form.email }}
        <div class="authorization-label">{{ form.password1.label }}</div>
        {{ form.password1 }}
        <div class="authorization-label">{{ form.password2.label }}</div>
        {{ form.password2 }}
        <input type="hidden" name="next" value="{{ next }}" />
        <input class="authorization-submit" type="submit" value="Зарегистрироваться">
    </form>
</div>
{% include "main/footer.html" %}

bowlingvo/main/templates/main/section_page.html
{% include "main/header.html" %}

<div class='page-head'>
    <div class='go-back'><a href="{% url 'language' language_name=language.url_name %}"><</a></div>
	<div class='page-name'>
		{{ section.name }}
	</div>
</div>

<div id='lex-lessons'>
    {% for lesson, ability in lessons %}
	<div class='{{ ability }} lex-lesson-path'>
		>
	</div>
	<div class='{{ ability }} lex-lesson'>
		{% if ability == 'finished' %}
            <a href="{% url 'lesson' language_name=language.url_name section_name=section.url_name lesson_order=lesson.order %}">
        {% elif ability == 'active' %}
            <a href="{% url 'lesson' language_name=language.url_name section_name=section.url_name lesson_order=lesson.order %}">
        {% endif %}
			<div class='lex-lesson-name'>
				{{ lesson.order }}
			</div>
			<div class='lesson-start-button'>
			{% if ability == 'finished' %}
				Повторить
			{% elif ability == 'active' %}
				Начать
			{% else %}
				Недоступен
			{% endif %}
			</div>
        </a></div>
    {% endfor %}
</div>

{% include "main/footer.html" %}

bowlingvo/main/templates/main/sorry.html
{% include "main/header.html" %}

Данная страница находится в разработке<br>
Приносим извинения за доставленные неудобства<br>
<a href="{% url 'index' %}">На главную</a>

{% include "main/footer.html" %}